api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
        jsonhal:  ['application/hal+json']

    # enabled graphQL
    graphql:
        graphiql:
            enabled: true

    # pagination config
    collection:
        pagination:
            items_per_page: 10

    # filter
#    player.date_filter:
#        parent: 'api_platform.doctrine.orm.date_filter'
#        arguments: [ { dateProperty: ~ } ]
#        tags:  [ 'api_platform.filter' ]
#        # The following are mandatory only if a _defaults section is defined
#        # You may want to isolate filters in a dedicated file to avoid adding them
#        autowire: false
#        autoconfigure: false
#        public: false
